ALTER TABLE RESTAURANT ADD horizontal VARCHAR(350) DEFAULT NULL;
ALTER TABLE RESTAURANT ADD vertical VARCHAR(360) DEFAULT NULL;

-- ALTER TABLE RESTAURANT MODIFY imagehorizontal VARCHAR(350) DEFAULT NULL;
-- ALTER TABLE RESTAURANT MODIFY imagevertical VARCHAR(360) DEFAULT NULL;

    -- imagehorizontal VARCHAR(300) DEFAULT NULL, 
    -- imagevertical VARCHAR(300) DEFAULT NULL,
